language: python 

python:
  - "2.7"

install:
  - pip install pipenv
  - pip install coveralls

script:
- nosetests
- coverage run --source=. -m py.test && coverage report
- coveralls

after_success: coveralls
cache: pip

